baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'FranciscoSP Theme'

[params]
home.pageCount = 5

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30

[module]
[module.hugoVersion]
extended = true
min = "0.116.0"
