name = 'FranciscoSP Theme'
license = 'MIT'
licenselink = 'https://github.com/pacismo/franciscosp-theme/LICENSE'
description = 'A theme I worked on for my website'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/pacismo/franciscosp-theme'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Francisco Santana'
  homepage = 'https://franciscosp.com/'
